<div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <th scope="col">Customer Name</th>
                                <th scope="col">Customer Address</th>
                                <th scope="col">Zipcode</th> 
                                <th scope="col">Products</th>
                                <th scope="col">Quantity</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                                foreach($data as $k => $v){
                                    echo '<tr><td>'.$v->customer_name.'</td>
                                    <td>'.$v->customer_address.'</td>
                                    <td>'.$v->zipcode.'</td>
                                    <td>'.$v->product.'</td>
                                    <td>'.$v->quantity.'</td>
                                    </tr>';
                                }
                            ?>

                        </tbody>

                        
                    </table>
                    <a href="/index">Main Page</a>
                </div>