

<h2>Add Orders</h2>
<!-- <div class="alert alert-<?php echo $success === true ? 'success' : 'danger'; ?>">
    <?php //echo isset($message)?$message:''; ?>
</div> -->

<?php echo $this->tag->form("orderadd/orders"); ?>
<p>
    <label for="customer_name">Customer Name</label>
    <?php echo $this->tag->textField("customer_name"); ?>
</p>
<p>
    <label for="customer_address">Customer Address</label>
    <?php echo $this->tag->textField("customer_address"); ?>
</p>
<p>
    <label for="zipcode">Zipcode</label>
    <?php echo $this->tag->textField("zipcode"); ?>
</p>
<p>
    <label for="product">Product</label>
    <?php echo $this->tag->select(
    [
        'product',
        $data,
        'using'      => [
            'id', 
            'name',
        ]
    ]
); ?>
</p>
<p>
    <label for="quantity">Quantity</label>
    <?php echo $this->tag->textField("quantity"); ?>
</p>

<?php echo $this->tag->submitButton("Submit"); ?>
<p>
    <a href="/index">Main Page</a>
</p>
</form>