<div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <th scope="col">name</th>
                                <th scope="col">description</th>
                                <th scope="col">price</th> 
                                <th scope="col">tags</th>
                                <th scope="col">stocks</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                                foreach($data as $k => $v){
                                    echo '<tr><td>'.$v->name.'</td>
                                    <td>'.$v->description.'</td>
                                    <td>'.$v->price.'</td>
                                    <td>'.$v->tags.'</td>
                                    <td>'.$v->stocks.'</td>
                                    </tr>';
                                }
                            ?>

                        </tbody>

                        
                    </table>
                    <a href="/index">Main Page</a>
                </div>